import re

NEW_EXERCISES = """
export const EXERCISE_DATABASE: Exercise[] = [
    // ── CHEST & PUSH ────────────────────────────────────────────────────────
    { id: "push_up", name: "Push-Up", muscleGroup: "chest", secondaryMuscles: ["triceps", "shoulders"], equipment: ["bodyweight"], difficulty: 1, isCompound: true, modality: "strength", instructions: "Hands shoulder-width, lower chest to floor, press back.", imageUrl: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=200&q=40", cue: "Full ROM — chest grazes floor" },
    { id: "wide_push_up", name: "Wide Push-Up", muscleGroup: "chest", secondaryMuscles: ["shoulders"], equipment: ["bodyweight"], difficulty: 1, isCompound: true, modality: "strength", instructions: "Hands wider than shoulder-width, emphasises outer chest.", imageUrl: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=200&q=40" },
    { id: "close_push_up", name: "Close-Grip Push-Up", muscleGroup: "triceps", secondaryMuscles: ["chest"], equipment: ["bodyweight"], difficulty: 1, isCompound: true, modality: "strength", instructions: "Hands together under chest, elbows tight to sides.", imageUrl: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=200&q=40" },
    { id: "incline_push_up", name: "Incline Push-Up", muscleGroup: "chest", secondaryMuscles: ["triceps"], equipment: ["bench", "chair"], difficulty: 1, isCompound: true, modality: "strength", instructions: "Hands elevated on bench, lower chest press angle.", imageUrl: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=200&q=40" },
    { id: "decline_push_up", name: "Decline Push-Up", muscleGroup: "chest", secondaryMuscles: ["triceps", "shoulders"], equipment: ["bench", "chair"], difficulty: 2, isCompound: true, modality: "strength", instructions: "Feet elevated, hands on floor — upper chest focus.", imageUrl: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=200&q=40" },
    { id: "archer_push_up", name: "Archer Push-Up", muscleGroup: "chest", secondaryMuscles: ["triceps"], equipment: ["bodyweight"], difficulty: 3, isCompound: true, modality: "strength", instructions: "Wide stance, lean to one side and press; alternate sides.", imageUrl: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=200&q=40" },
    { id: "pike_push_up", name: "Pike Push-Up", muscleGroup: "shoulders", secondaryMuscles: ["triceps"], equipment: ["bodyweight"], difficulty: 2, isCompound: true, modality: "strength", instructions: "Hips high in inverted V, lower crown toward floor.", imageUrl: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=200&q=40" },
    { id: "pseudo_planche", name: "Pseudo Planche Push-Up", muscleGroup: "chest", secondaryMuscles: ["shoulders", "core"], equipment: ["bodyweight"], difficulty: 3, isCompound: true, modality: "strength", instructions: "Fingers back, lean forward, lower slowly.", imageUrl: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=200&q=40" },
    { id: "diamond_push_up", name: "Diamond Push-Up", muscleGroup: "triceps", secondaryMuscles: ["chest"], equipment: ["bodyweight"], difficulty: 2, isCompound: true, modality: "strength", instructions: "Thumbs & index fingers form diamond shape on floor.", imageUrl: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=200&q=40" },
    { id: "spiderman_push_up", name: "Spiderman Push-Up", muscleGroup: "chest", secondaryMuscles: ["core", "obliques"], equipment: ["bodyweight"], difficulty: 2, isCompound: true, modality: "strength", instructions: "Bring knee to elbow as you lower; alternate sides.", imageUrl: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=200&q=40" },
    { id: "clap_push_up", name: "Clap Push-Up", muscleGroup: "chest", secondaryMuscles: ["triceps", "shoulders"], equipment: ["bodyweight"], difficulty: 3, isCompound: false, modality: "plyometric", instructions: "Explosive press so hands leave floor; clap mid-air.", imageUrl: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=200&q=40" },
    { id: "typewriter_push_up", name: "Typewriter Push-Up", muscleGroup: "chest", secondaryMuscles: ["shoulders"], equipment: ["bodyweight"], difficulty: 3, isCompound: true, modality: "strength", instructions: "Lower to one side, glide chest across floor, press on other side.", imageUrl: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=200&q=40" },
    { id: "hindu_push_up", name: "Hindu Push-Up", muscleGroup: "chest", secondaryMuscles: ["shoulders", "triceps", "core"], equipment: ["bodyweight"], difficulty: 2, isCompound: true, modality: "mobility", instructions: "Swoop down from downward dog into upward dog.", imageUrl: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=200&q=40" },
    { id: "dive_bomber", name: "Dive Bomber Push-Up", muscleGroup: "shoulders", secondaryMuscles: ["chest", "triceps"], equipment: ["bodyweight"], difficulty: 3, isCompound: true, modality: "strength", instructions: "Hindu push-up, but reverse the swoop back to start.", imageUrl: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=200&q=40" },
    { id: "explosive_negative", name: "Explosive Negative Push", muscleGroup: "chest", secondaryMuscles: ["triceps"], equipment: ["bodyweight"], difficulty: 2, isCompound: true, modality: "plyometric", instructions: "Slowly lower for 5s, explosively press up.", imageUrl: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=200&q=40" },
    { id: "chest_dip", name: "Chest Dip", muscleGroup: "chest", secondaryMuscles: ["triceps", "shoulders"], equipment: ["chair"], difficulty: 2, isCompound: true, modality: "strength", instructions: "Lean forward on parallel bars or sturdy chairs, lower body.", imageUrl: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=200&q=40" },
    { id: "tricep_dip", name: "Bench Dip", muscleGroup: "triceps", secondaryMuscles: ["shoulders"], equipment: ["chair", "bench"], difficulty: 1, isCompound: true, modality: "strength", instructions: "Hands on bench edge behind you, lower hips to floor.", imageUrl: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=200&q=40" },
    { id: "db_bench_press", name: "Dumbbell Bench Press", muscleGroup: "chest", secondaryMuscles: ["triceps", "shoulders"], equipment: ["dumbbell", "bench"], difficulty: 1, isCompound: true, modality: "strength", instructions: "Lie on bench, press dumbbells over chest.", imageUrl: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=200&q=40" },
    { id: "db_incline_press", name: "Incline DB Press", muscleGroup: "chest", secondaryMuscles: ["shoulders", "triceps"], equipment: ["dumbbell", "bench"], difficulty: 2, isCompound: true, modality: "strength", instructions: "Bench at 30-45 deg, press dumbbells targeting upper chest.", imageUrl: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=200&q=40" },
    { id: "db_chest_fly", name: "DB Chest Fly", muscleGroup: "chest", secondaryMuscles: ["shoulders"], equipment: ["dumbbell", "bench"], difficulty: 2, isCompound: false, modality: "strength", instructions: "Slight bend in elbows, open arms wide to stretch chest.", imageUrl: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=200&q=40" },
    { id: "band_chest_press", name: "Band Chest Press", muscleGroup: "chest", secondaryMuscles: ["triceps"], equipment: ["resistance_band"], difficulty: 1, isCompound: true, modality: "strength", instructions: "Anchor band behind you, press handles forward.", imageUrl: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=200&q=40" },
    { id: "band_fly", name: "Band Chest Fly", muscleGroup: "chest", secondaryMuscles: [], equipment: ["resistance_band"], difficulty: 1, isCompound: false, modality: "strength", instructions: "Squeeze bands together in a hugging motion.", imageUrl: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=200&q=40" },

    // ── BACK & PULL ────────────────────────────────────────────────────────
    { id: "pull_up", name: "Pull-Up", muscleGroup: "back", secondaryMuscles: ["biceps", "forearms"], equipment: ["pull_up_bar"], difficulty: 2, isCompound: true, modality: "strength", instructions: "Overhand grip, pull chin over bar.", imageUrl: "https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=200&q=40", cue: "Drive elbows to the floor" },
    { id: "chin_up", name: "Chin-Up", muscleGroup: "biceps", secondaryMuscles: ["back", "forearms"], equipment: ["pull_up_bar"], difficulty: 2, isCompound: true, modality: "strength", instructions: "Underhand grip, pull chin over bar.", imageUrl: "https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=200&q=40" },
    { id: "wide_pull_up", name: "Wide Pull-Up", muscleGroup: "back", secondaryMuscles: ["biceps"], equipment: ["pull_up_bar"], difficulty: 3, isCompound: true, modality: "strength", instructions: "Grip wider than shoulders to target lats heavily.", imageUrl: "https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=200&q=40" },
    { id: "neutral_pull_up", name: "Neutral Grip Pull-Up", muscleGroup: "back", secondaryMuscles: ["biceps"], equipment: ["pull_up_bar"], difficulty: 2, isCompound: true, modality: "strength", instructions: "Palms facing each other, strong activation of lower lats.", imageUrl: "https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=200&q=40" },
    { id: "australian_pull_up", name: "Inverted Row", muscleGroup: "back", secondaryMuscles: ["biceps", "rear_delts"], equipment: ["chair", "pull_up_bar"], difficulty: 1, isCompound: true, modality: "strength", instructions: "Body horizontal under low bar or table, pull chest up.", imageUrl: "https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=200&q=40" },
    { id: "towel_row", name: "Doorway Towel Row", muscleGroup: "back", secondaryMuscles: ["biceps", "forearms"], equipment: ["towel", "wall"], difficulty: 1, isCompound: true, modality: "strength", instructions: "Wrap towel around door handle, lean back, pull body forward.", imageUrl: "https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=200&q=40" },
    { id: "superman", name: "Superman Hold", muscleGroup: "back", secondaryMuscles: ["glutes", "hamstrings"], equipment: ["floor"], difficulty: 1, isCompound: false, modality: "isometric", instructions: "Lie on stomach, raise arms and legs off the floor.", imageUrl: "https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=200&q=40", duration_s: 30 },
    { id: "superman_reps", name: "Superman Extensions", muscleGroup: "back", secondaryMuscles: ["glutes"], equipment: ["floor"], difficulty: 1, isCompound: false, modality: "strength", instructions: "Lie prone, repetitively lift chest and thighs off floor.", imageUrl: "https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=200&q=40" },
    { id: "snow_angels", name: "Reverse Snow Angels", muscleGroup: "back", secondaryMuscles: ["shoulders"], equipment: ["floor"], difficulty: 1, isCompound: false, modality: "mobility", instructions: "Prone, hover arms in wide arc from hips to overhead.", imageUrl: "https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=200&q=40" },
    { id: "ytw_raises", name: "Y-T-W Raises", muscleGroup: "shoulders", secondaryMuscles: ["back", "rhomboids"], equipment: ["floor"], difficulty: 2, isCompound: false, modality: "strength", instructions: "Prone, trace Y, T, and W shapes with arms.", imageUrl: "https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=200&q=40" },
    { id: "front_lever_tucks", name: "Front Lever Tucks", muscleGroup: "core", secondaryMuscles: ["back", "lats"], equipment: ["pull_up_bar"], difficulty: 3, isCompound: true, modality: "isometric", instructions: "Hang from bar, tuck knees to chest and lean back parallel to floor.", imageUrl: "https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=200&q=40" },
    { id: "muscle_up", name: "Muscle-Up", muscleGroup: "back", secondaryMuscles: ["chest", "triceps", "core"], equipment: ["pull_up_bar"], difficulty: 3, isCompound: true, modality: "plyometric", instructions: "Explosive pullup transitioning into a straight bar dip.", imageUrl: "https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=200&q=40" },
    { id: "scapular_pull", name: "Scapular Pull-Ups", muscleGroup: "back", secondaryMuscles: ["traps"], equipment: ["pull_up_bar"], difficulty: 1, isCompound: false, modality: "strength", instructions: "Dead hang, retract shoulder blades together without bending elbows.", imageUrl: "https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=200&q=40" },
    { id: "neg_pull_up", name: "Negative Pull-Ups", muscleGroup: "back", secondaryMuscles: ["biceps"], equipment: ["pull_up_bar"], difficulty: 1, isCompound: true, modality: "strength", instructions: "Jump chin over bar, lower down as slowly as possible (5-10s).", imageUrl: "https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=200&q=40" },
    { id: "db_row", name: "DB Single-Arm Row", muscleGroup: "back", secondaryMuscles: ["biceps", "core"], equipment: ["dumbbell", "bench"], difficulty: 1, isCompound: true, modality: "strength", instructions: "Supported on bench, row dumbbell to hip.", imageUrl: "https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=200&q=40" },
    { id: "db_pullover", name: "DB Pullover", muscleGroup: "back", secondaryMuscles: ["chest", "core"], equipment: ["dumbbell", "bench", "floor"], difficulty: 2, isCompound: true, modality: "strength", instructions: "Lie flat, pull weight from behind head to over chest.", imageUrl: "https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=200&q=40" },
    { id: "band_pulldown", name: "Band Lat Pulldown", muscleGroup: "back", secondaryMuscles: ["biceps"], equipment: ["resistance_band"], difficulty: 1, isCompound: true, modality: "strength", instructions: "Band anchored high, pull elbows down to ribs.", imageUrl: "https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=200&q=40" },

    // ── SHOULDERS ────────────────────────────────────────────────────────
    { id: "handstand_push_up", name: "Handstand Push-Up", muscleGroup: "shoulders", secondaryMuscles: ["triceps", "core"], equipment: ["wall"], difficulty: 3, isCompound: true, modality: "strength", instructions: "Kick up against wall, lower head to floor, press back up.", imageUrl: "https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?w=200&q=40" },
    { id: "handstand_hold", name: "Handstand Hold", muscleGroup: "shoulders", secondaryMuscles: ["core", "triceps", "forearms"], equipment: ["wall"], difficulty: 2, isCompound: true, modality: "isometric", instructions: "Hold a wall-assisted or freestanding handstand.", imageUrl: "https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?w=200&q=40", duration_s: 30 },
    { id: "wall_walk", name: "Wall Walk", muscleGroup: "shoulders", secondaryMuscles: ["core", "chest"], equipment: ["wall"], difficulty: 2, isCompound: true, modality: "strength", instructions: "Start push-up position, walk feet up wall stepping hands backward.", imageUrl: "https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?w=200&q=40" },
    { id: "db_ohp", name: "DB Overhead Press", muscleGroup: "shoulders", secondaryMuscles: ["triceps"], equipment: ["dumbbell"], difficulty: 1, isCompound: true, modality: "strength", instructions: "Seated or standing, press dumbbells overhead.", imageUrl: "https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?w=200&q=40" },
    { id: "db_lateral_raise", name: "DB Lateral Raise", muscleGroup: "shoulders", secondaryMuscles: ["traps"], equipment: ["dumbbell"], difficulty: 1, isCompound: false, modality: "strength", instructions: "Raise dumbbells straight out to the sides.", imageUrl: "https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?w=200&q=40" },
    { id: "db_front_raise", name: "DB Front Raise", muscleGroup: "shoulders", secondaryMuscles: ["chest"], equipment: ["dumbbell"], difficulty: 1, isCompound: false, modality: "strength", instructions: "Raise dumbbells forward to eye level.", imageUrl: "https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?w=200&q=40" },
    { id: "reverse_pec_deck", name: "Reverse Fly / Rear Delt Raise", muscleGroup: "shoulders", secondaryMuscles: ["back"], equipment: ["dumbbell", "floor"], difficulty: 2, isCompound: false, modality: "strength", instructions: "Hinge forward, raise weights back to target rear delts.", imageUrl: "https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?w=200&q=40" },
    { id: "lu_raise", name: "Lu Raise", muscleGroup: "shoulders", secondaryMuscles: ["traps"], equipment: ["dumbbell"], difficulty: 2, isCompound: false, modality: "strength", instructions: "Lateral raise but continue full ROM to touch plates overhead.", imageUrl: "https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?w=200&q=40" },
    { id: "cuban_press", name: "Cuban Press", muscleGroup: "shoulders", secondaryMuscles: ["rotator_cuff"], equipment: ["dumbbell", "floor"], difficulty: 2, isCompound: true, modality: "strength", instructions: "Upright row -> external rotation -> overhead press.", imageUrl: "https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?w=200&q=40" },
    { id: "band_face_pull", name: "Band Face Pull", muscleGroup: "shoulders", secondaryMuscles: ["back", "traps"], equipment: ["resistance_band"], difficulty: 1, isCompound: true, modality: "strength", instructions: "Pull band to forehead, elbows high, squeeze shoulder blades.", imageUrl: "https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?w=200&q=40" },

    // ── LEGS & GLUTES ──────────────────────────────────────────────────────
    { id: "squat", name: "Bodyweight Squat", muscleGroup: "quads", secondaryMuscles: ["glutes", "hamstrings", "core"], equipment: ["bodyweight"], difficulty: 1, isCompound: true, modality: "strength", instructions: "Drop hips down and back, keep chest up, drive through heels.", imageUrl: "https://images.unsplash.com/photo-1434608519344-49d77a699e1d?w=200&q=40", cue: "Break parallel" },
    { id: "jump_squat", name: "Jump Squat", muscleGroup: "quads", secondaryMuscles: ["glutes", "calves"], equipment: ["bodyweight"], difficulty: 2, isCompound: true, modality: "plyometric", instructions: "Squat down and explode upward, landing softly.", imageUrl: "https://images.unsplash.com/photo-1434608519344-49d77a699e1d?w=200&q=40" },
    { id: "lunge", name: "Walking Lunge", muscleGroup: "quads", secondaryMuscles: ["glutes", "hamstrings"], equipment: ["bodyweight"], difficulty: 1, isCompound: true, modality: "strength", instructions: "Step forward, drop back knee to floor, push off front heel.", imageUrl: "https://images.unsplash.com/photo-1434608519344-49d77a699e1d?w=200&q=40" },
    { id: "reverse_lunge", name: "Reverse Lunge", muscleGroup: "glutes", secondaryMuscles: ["quads", "hamstrings"], equipment: ["bodyweight"], difficulty: 1, isCompound: true, modality: "strength", instructions: "Step backward, drop back knee. More glute and knee-friendly.", imageUrl: "https://images.unsplash.com/photo-1434608519344-49d77a699e1d?w=200&q=40" },
    { id: "pistol_squat", name: "Pistol Squat (1-Leg)", muscleGroup: "quads", secondaryMuscles: ["glutes", "core"], equipment: ["bodyweight"], difficulty: 3, isCompound: true, modality: "strength", instructions: "Balance on one leg, extend other leg forward, squat fully.", imageUrl: "https://images.unsplash.com/photo-1434608519344-49d77a699e1d?w=200&q=40" },
    { id: "bulgarian_split_squat", name: "Bulgarian Split Squat", muscleGroup: "quads", secondaryMuscles: ["glutes"], equipment: ["chair", "bench"], difficulty: 2, isCompound: true, modality: "strength", instructions: "Back foot elevated on chair, drop hips straight down.", imageUrl: "https://images.unsplash.com/photo-1434608519344-49d77a699e1d?w=200&q=40" },
    { id: "shrimp_squat", name: "Shrimp Squat", muscleGroup: "quads", secondaryMuscles: ["glutes", "core"], equipment: ["bodyweight"], difficulty: 3, isCompound: true, modality: "strength", instructions: "Hold one heel behind you, lower that knee to the floor.", imageUrl: "https://images.unsplash.com/photo-1434608519344-49d77a699e1d?w=200&q=40" },
    { id: "cossack_squat", name: "Cossack Squat", muscleGroup: "quads", secondaryMuscles: ["adductors", "glutes"], equipment: ["bodyweight"], difficulty: 2, isCompound: true, modality: "mobility", instructions: "Wide stance, deep side lunge keeping one leg perfectly straight.", imageUrl: "https://images.unsplash.com/photo-1434608519344-49d77a699e1d?w=200&q=40" },
    { id: "glute_bridge", name: "Glute Bridge", muscleGroup: "glutes", secondaryMuscles: ["hamstrings", "lower_back"], equipment: ["floor"], difficulty: 1, isCompound: true, modality: "strength", instructions: "Lie on back, knees bent, drive hips up squeezing glutes.", imageUrl: "https://images.unsplash.com/photo-1434608519344-49d77a699e1d?w=200&q=40" },
    { id: "single_leg_bridge", name: "Single-Leg Glute Bridge", muscleGroup: "glutes", secondaryMuscles: ["hamstrings", "core"], equipment: ["floor"], difficulty: 2, isCompound: true, modality: "strength", instructions: "One leg extended straight, drive hips up with the other leg.", imageUrl: "https://images.unsplash.com/photo-1434608519344-49d77a699e1d?w=200&q=40" },
    { id: "nordic_curl", name: "Nordic Hamstring Curl", muscleGroup: "hamstrings", secondaryMuscles: ["glutes", "calves"], equipment: ["bodyweight", "floor"], difficulty: 3, isCompound: true, modality: "strength", instructions: "Ankles anchored, slowly fall forward strictly relying on hamstrings.", imageUrl: "https://images.unsplash.com/photo-1434608519344-49d77a699e1d?w=200&q=40" },
    { id: "sliding_leg_curl", name: "Sliding Leg Curl", muscleGroup: "hamstrings", secondaryMuscles: ["glutes"], equipment: ["towel", "floor"], difficulty: 2, isCompound: true, modality: "strength", instructions: "Bridge position with heels on towel. Slide out and pull back.", imageUrl: "https://images.unsplash.com/photo-1434608519344-49d77a699e1d?w=200&q=40" },
    { id: "calf_raise", name: "Calf Raises", muscleGroup: "calves", secondaryMuscles: [], equipment: ["bodyweight", "wall"], difficulty: 1, isCompound: false, modality: "strength", instructions: "Rise fully onto toes, hold 1s, lower slowly.", imageUrl: "https://images.unsplash.com/photo-1434608519344-49d77a699e1d?w=200&q=40" },
    { id: "single_calf_raise", name: "Single-Leg Calf Raise", muscleGroup: "calves", secondaryMuscles: [], equipment: ["bodyweight", "wall"], difficulty: 2, isCompound: false, modality: "strength", instructions: "Stand on one leg, rise onto toes, full stretch at bottom.", imageUrl: "https://images.unsplash.com/photo-1434608519344-49d77a699e1d?w=200&q=40" },
    { id: "wall_sit", name: "Wall Sit Hold", muscleGroup: "quads", secondaryMuscles: ["glutes", "core"], equipment: ["wall"], difficulty: 1, isCompound: true, modality: "isometric", instructions: "Back flat against wall, knees 90 degrees.", imageUrl: "https://images.unsplash.com/photo-1434608519344-49d77a699e1d?w=200&q=40", duration_s: 45 },
    { id: "db_goblet_squat", name: "Goblet Squat", muscleGroup: "quads", secondaryMuscles: ["glutes", "core"], equipment: ["dumbbell"], difficulty: 1, isCompound: true, modality: "strength", instructions: "Hold DB vertically at chest, squat very deep.", imageUrl: "https://images.unsplash.com/photo-1434608519344-49d77a699e1d?w=200&q=40" },
    { id: "db_rdl", name: "DB Romanian Deadlift", muscleGroup: "hamstrings", secondaryMuscles: ["glutes", "lower_back"], equipment: ["dumbbell"], difficulty: 2, isCompound: true, modality: "strength", instructions: "Hinge at hips, keep back flat, stretch hamstrings.", imageUrl: "https://images.unsplash.com/photo-1434608519344-49d77a699e1d?w=200&q=40" },
    { id: "box_jump", name: "Box Jumps", muscleGroup: "quads", secondaryMuscles: ["glutes", "calves", "core"], equipment: ["chair", "bench"], difficulty: 3, isCompound: true, modality: "plyometric", instructions: "Explosive jump onto a sturdy elevated surface. Step down.", imageUrl: "https://images.unsplash.com/photo-1434608519344-49d77a699e1d?w=200&q=40" },

    // ── CORE & ABS ─────────────────────────────────────────────────────────
    { id: "plank", name: "Forearm Plank", muscleGroup: "core", secondaryMuscles: ["shoulders", "glutes"], equipment: ["floor"], difficulty: 1, isCompound: true, modality: "isometric", instructions: "Hold rigid straight body on forearms and toes.", imageUrl: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=200&q=40", duration_s: 60, cue: "Squeeze glutes and brace" },
    { id: "hollow_body_hold", name: "Hollow Body Hold", muscleGroup: "core", secondaryMuscles: ["lower_back"], equipment: ["floor"], difficulty: 2, isCompound: false, modality: "isometric", instructions: "Lie on back, press lumbar into floor, lift shoulders and straight legs 6 inches.", imageUrl: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=200&q=40", duration_s: 45 },
    { id: "hollow_body_rocks", name: "Hollow Body Rocks", muscleGroup: "core", secondaryMuscles: ["lower_back"], equipment: ["floor"], difficulty: 3, isCompound: false, modality: "isometric", instructions: "Maintain hollow body shape and smoothly rock back and forth.", imageUrl: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=200&q=40" },
    { id: "l_sit", name: "L-Sit", muscleGroup: "core", secondaryMuscles: ["triceps", "hip_flexors", "quads"], equipment: ["floor", "chair"], difficulty: 3, isCompound: true, modality: "isometric", instructions: "Support weight on hands, lift legs straight out perfectly parallel to floor.", imageUrl: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=200&q=40", duration_s: 15 },
    { id: "hanging_leg_raise", name: "Hanging Leg Raises", muscleGroup: "core", secondaryMuscles: ["grip", "hip_flexors"], equipment: ["pull_up_bar"], difficulty: 2, isCompound: true, modality: "strength", instructions: "Hang from bar, raise straight legs to 90 degrees.", imageUrl: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=200&q=40" },
    { id: "hanging_knee_raise", name: "Hanging Knee Tucks", muscleGroup: "core", secondaryMuscles: ["grip", "hip_flexors"], equipment: ["pull_up_bar"], difficulty: 1, isCompound: true, modality: "strength", instructions: "Hang from bar, tuck knees tightly into chest.", imageUrl: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=200&q=40" },
    { id: "dragon_flag", name: "Dragon Flag", muscleGroup: "core", secondaryMuscles: ["lats", "glutes"], equipment: ["bench", "floor"], difficulty: 3, isCompound: true, modality: "strength", instructions: "Anchor hands behind head, raise totally rigid body up to shoulders.", imageUrl: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=200&q=40" },
    { id: "dead_bug", name: "Dead Bugs", muscleGroup: "core", secondaryMuscles: ["hip_flexors"], equipment: ["floor"], difficulty: 1, isCompound: false, modality: "strength", instructions: "Lie on back, lower opposite arm and leg to floor while bracing abs.", imageUrl: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=200&q=40" },
    { id: "crunch", name: "Crunches", muscleGroup: "core", secondaryMuscles: [], equipment: ["floor"], difficulty: 1, isCompound: false, modality: "strength", instructions: "Lie on back, knees bent, peel shoulder blades off floor.", imageUrl: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=200&q=40" },
    { id: "ab_wheel_rollout", name: "Ab Wheel / Towel Rollout", muscleGroup: "core", secondaryMuscles: ["lats", "shoulders"], equipment: ["floor", "towel"], difficulty: 3, isCompound: true, modality: "strength", instructions: "From knees, roll hands forward until chest hovers floor, pull back.", imageUrl: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=200&q=40" },

    // ── OBLIQUES (Newly Added) ─────────────────────────────────────────────
    { id: "russian_twist", name: "Russian Twists", muscleGroup: "obliques", secondaryMuscles: ["core"], equipment: ["bodyweight", "floor", "dumbbell"], difficulty: 1, isCompound: false, modality: "strength", instructions: "Sit in V-shape, tap hands on floor outside each hip rhythmically.", imageUrl: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=200&q=40" },
    { id: "side_plank", name: "Side Plank", muscleGroup: "obliques", secondaryMuscles: ["shoulders", "core"], equipment: ["floor"], difficulty: 1, isCompound: true, modality: "isometric", instructions: "Support body on one forearm and side of foot. Keep body totally straight.", imageUrl: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=200&q=40", duration_s: 45 },
    { id: "side_plank_dips", name: "Side Plank Hip Dips", muscleGroup: "obliques", secondaryMuscles: ["core"], equipment: ["floor"], difficulty: 2, isCompound: false, modality: "strength", instructions: "From side plank, lower hip to tap floor, then raise high.", imageUrl: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=200&q=40" },
    { id: "bicycle_crunch", name: "Bicycle Crunches", muscleGroup: "obliques", secondaryMuscles: ["core", "hip_flexors"], equipment: ["floor"], difficulty: 1, isCompound: false, modality: "strength", instructions: "Opposite elbow to opposite knee with a deliberate full torso twist.", imageUrl: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=200&q=40" },
    { id: "woodchopper", name: "Standing Woodchoppers", muscleGroup: "obliques", secondaryMuscles: ["core", "shoulders"], equipment: ["resistance_band", "dumbbell"], difficulty: 2, isCompound: true, modality: "strength", instructions: "Rotate torso aggressively diagonally downwards like swinging an axe.", imageUrl: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=200&q=40" },
    { id: "windshield_wipers", name: "Floor Windshield Wipers", muscleGroup: "obliques", secondaryMuscles: ["core"], equipment: ["floor"], difficulty: 3, isCompound: true, modality: "strength", instructions: "Lie on back, legs straight up, slowly lower stacked legs side to side.", imageUrl: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=200&q=40" },
    { id: "hanging_wiper", name: "Hanging Windshield Wipers", muscleGroup: "obliques", secondaryMuscles: ["core", "lats"], equipment: ["pull_up_bar"], difficulty: 3, isCompound: true, modality: "strength", instructions: "Hang from bar, raise legs to bar level, rotate side to side fully.", imageUrl: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=200&q=40" },

    // ── LOWER BACK ─────────────────────────────────────────────────────────
    { id: "bird_dog", name: "Bird Dogs", muscleGroup: "lower_back", secondaryMuscles: ["core", "glutes"], equipment: ["floor"], difficulty: 1, isCompound: false, modality: "strength", instructions: "Tabletop position, extend right arm and left leg, squeeze.", imageUrl: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=200&q=40" },
    { id: "back_extension", name: "Floor Back Extensions", muscleGroup: "lower_back", secondaryMuscles: ["glutes"], equipment: ["floor"], difficulty: 1, isCompound: false, modality: "strength", instructions: "Prone, hands behind head, arch back to lift chest cleanly off the floor.", imageUrl: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=200&q=40" },
    { id: "good_morning", name: "DB Good Mornings", muscleGroup: "lower_back", secondaryMuscles: ["hamstrings"], equipment: ["dumbbell"], difficulty: 2, isCompound: true, modality: "strength", instructions: "Hold weight at chest, slight knee bend, pure hip hinge keeping back flat.", imageUrl: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=200&q=40" },

    // ── CARDIO & HIIT ──────────────────────────────────────────────────────
    { id: "burpee", name: "Burpees", muscleGroup: "cardio", secondaryMuscles: ["chest", "quads", "core"], equipment: ["bodyweight"], difficulty: 2, isCompound: true, modality: "cardio", instructions: "Drop to floor (chest touches), jump up, clap overhead.", imageUrl: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=200&q=40" },
    { id: "mountain_climber", name: "Mountain Climbers", muscleGroup: "cardio", secondaryMuscles: ["core", "shoulders"], equipment: ["bodyweight", "floor"], difficulty: 1, isCompound: true, modality: "cardio", instructions: "Push-up position, sprint knees to chest rapidly.", imageUrl: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=200&q=40", duration_s: 45 },
    { id: "jumping_jack", name: "Jumping Jacks", muscleGroup: "cardio", secondaryMuscles: ["calves"], equipment: ["bodyweight"], difficulty: 1, isCompound: true, modality: "cardio", instructions: "Classic star jump.", imageUrl: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=200&q=40", duration_s: 60 },
    { id: "high_knees", name: "High Knees", muscleGroup: "cardio", secondaryMuscles: ["core", "hip_flexors"], equipment: ["bodyweight"], difficulty: 2, isCompound: true, modality: "cardio", instructions: "Sprint in place, driving knees to waist height.", imageUrl: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=200&q=40", duration_s: 45 },
    { id: "jump_rope", name: "Invisible Jump Rope", muscleGroup: "cardio", secondaryMuscles: ["calves"], equipment: ["bodyweight"], difficulty: 1, isCompound: true, modality: "cardio", instructions: "Mimic jump rope motions rapidly on toes.", imageUrl: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=200&q=40", duration_s: 60 },
    { id: "kettlebell_swing", name: "DB/KB Swings", muscleGroup: "glutes", secondaryMuscles: ["hamstrings", "cardio", "lower_back"], equipment: ["dumbbell", "kettlebell"], difficulty: 2, isCompound: true, modality: "plyometric", instructions: "Explosive hip hinge driving the weight up (NOT arm raise).", imageUrl: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=200&q=40", duration_s: 45 },

    // ── BICEPS / ARMS ──────────────────────────────────────────────────────
    { id: "db_bicep_curl", name: "DB Bicep Curl", muscleGroup: "biceps", secondaryMuscles: ["forearms"], equipment: ["dumbbell"], difficulty: 1, isCompound: false, modality: "strength", instructions: "Stand tall, curl dumbbells with palms up.", imageUrl: "https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=200&q=40" },
    { id: "db_hammer_curl", name: "DB Hammer Curl", muscleGroup: "forearms", secondaryMuscles: ["biceps"], equipment: ["dumbbell"], difficulty: 1, isCompound: false, modality: "strength", instructions: "Curl dumbbells keeping palms facing each other (neutral grip).", imageUrl: "https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=200&q=40" },
    { id: "band_curl", name: "Band Bicep Curl", muscleGroup: "biceps", secondaryMuscles: [], equipment: ["resistance_band"], difficulty: 1, isCompound: false, modality: "strength", instructions: "Stand on band, curl handles upwards.", imageUrl: "https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=200&q=40" },
    { id: "pelican_curl", name: "Bodyweight Pelican Curl", muscleGroup: "biceps", secondaryMuscles: ["chest", "shoulders"], equipment: ["bodyweight", "chair"], difficulty: 3, isCompound: true, modality: "strength", instructions: "Very advanced ring/bar extension into a deep bicep stretch.", imageUrl: "https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=200&q=40" },
    { id: "tricep_extension", name: "DB Tricep Extension", muscleGroup: "triceps", secondaryMuscles: [], equipment: ["dumbbell"], difficulty: 1, isCompound: false, modality: "strength", instructions: "Overhead or lying (skullcrushers), bend strictly at elbows.", imageUrl: "https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=200&q=40" },
    { id: "band_tricep_pushdown", name: "Band Tricep Pushdown", muscleGroup: "triceps", secondaryMuscles: [], equipment: ["resistance_band"], difficulty: 1, isCompound: false, modality: "strength", instructions: "Anchor high, push handles down locking elbows.", imageUrl: "https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=200&q=40" }
];
"""

with open('src/lib/WorkoutEngine.ts', 'r') as f:
    orig = f.read()

start = orig.find('export const EXERCISE_DATABASE: Exercise[] = [')
if start == -1:
    print("Could not find start array")
    exit(1)
    
# Find the start of the next export, or EOF
end = orig.find('export const DEFAULT_WORKOUT', start)
if end == -1:
    end = orig.find('export ', start + 10)
if end == -1:
    end = len(orig)

new_content = orig[:start] + NEW_EXERCISES.strip() + "\n\n" + orig[end:]

with open('src/lib/WorkoutEngine.ts', 'w') as f:
    f.write(new_content)

print(f"Replaced {end - start} chars with new exercise DB ({len(NEW_EXERCISES)} chars).")
